name: Build APK (arm64-v8a unsigned)

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3.2.0
      with:
        cmdline-tools-version: '13114758'
        packages: |
          platforms;android-36.1
          build-tools;36.1.0
          platform-tools

    - name: Install NDK
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          --install "ndk;28.2.13676358"
        echo "NDK_HOME=$ANDROID_HOME/ndk/28.2.13676358" >> $GITHUB_ENV
        sed -i '10i\
            ndkVersion = "28.2.13676358"' \
          ${{ github.workspace }}/V2rayNG/app/build.gradle.kts

    - name: Restore cached libhevtun
      id: cache-libhevtun
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/libs
        key: libhevtun-${{ runner.os }}-${{ env.NDK_HOME }}-${{ hashFiles('.git/modules/hev-socks5-tunnel/HEAD') }}

    - name: Build libhevtun
      if: steps.cache-libhevtun.outputs.cache-hit != 'true'
      run: bash compile-hevtun.sh

    - name: Save libhevtun cache
      if: steps.cache-libhevtun.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/libs
        key: libhevtun-${{ runner.os }}-${{ env.NDK_HOME }}-${{ hashFiles('.git/modules/hev-socks5-tunnel/HEAD') }}

    - name: Copy libhevtun
      run: cp -r libs V2rayNG/app

    - name: Fetch AndroidLibXrayLite tag
      run: |
        pushd AndroidLibXrayLite
        TAG=$(git describe --tags --abbrev=0)
        echo "CURRENT_TAG=$TAG" >> $GITHUB_ENV
        popd

    - name: Download libv2ray
      uses: robinraju/release-downloader@v1.12
      with:
        repository: 2dust/AndroidLibXrayLite
        tag: ${{ env.CURRENT_TAG }}
        fileName: libv2ray.aar
        out-file-path: V2rayNG/app/libs/

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'

    - name: Build APK (arm64-v8a only, unsigned)
      run: |
        cd V2rayNG
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        chmod +x gradlew
        ./gradlew assembleRelease \
          -PabiFilters=arm64-v8a

    - name: Upload arm64-v8a unsigned APK
      uses: actions/upload-artifact@v4
      with:
        name: arm64-v8a-unsigned
        path: V2rayNG/app/build/outputs/apk/**/release/*arm64-v8a*-unsigned.apk
